# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTOjCi2-AXTjfuWYZqUYTxTgMk0rH068
"""

!pip install GoogleNews
from GoogleNews import GoogleNews
import pandas as pd
googlenews=GoogleNews(period='d')
googlenews.setlang('pt')

googlenews.search('UEFA champions league')
googlenews.result()
result=googlenews.result()
df=pd.DataFrame(result)
df.head()

